### ISSUE TITLE
Seeking Documentation for Customization

### ISSUE THREAD

**Issue by denimdragonfly** [Sigil-Ebook/BibiReader#1]
Is there any documentation for customizing the bibi interface? It's mentioned on the bibi site that it's "possible to Flexible customization
Margins, background color/image, page dimensions, vertical/horizontal feed direction, etc. You can freely arrange it and design a reading experience that matches the book."

I'm looking specifically on how to add a cover page preview and if there is an option for "lazy load" so that viewers can start looking at the ebook before it has fully loaded images.

**Comment by kevinhendricks** [comment]
Sorry, I am no expert on the BiBi Reader interface.  Most of the controls you are looking for are almost all css based.  So I would begin there and ask your question on the BibIReader github site.
